<?php
/**
 * Renders benches/RESULTS.md from a results.jsonl produced by benches/run.sh.
 *
 * Each input line is one JSON object emitted by tools/bench_compare.php (engine=sdsearch|zend)
 * or examples/bench_engine (engine=native), or a synthetic {"status":"skipped"} record. This
 * script groups them by workload → size → engine and prints Markdown tables with cross-engine
 * speedups. It is pure formatting: no measurement happens here.
 *
 * Usage: php tools/bench_report.php <results.jsonl>   # prints Markdown to stdout
 */

$path = $argv[1] ?? '';
if ($path === '' || !is_file($path)) {
    fwrite(STDERR, "usage: php tools/bench_report.php <results.jsonl>\n");
    exit(2);
}

// data[workload][n][engine] = row (assoc); skips tracked separately.
$data = [];
$skips = [];
foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
    $r = json_decode($line, true);
    if (!is_array($r) || !isset($r['engine'], $r['workload'], $r['n'])) { continue; }
    if (($r['status'] ?? '') === 'skipped') {
        $skips[] = $r;
        continue;
    }
    // native is emitted in two passes: 'time' (honest ms/rss) and 'heap' (accurate heap). Route
    // the heap pass to a separate slot so it does not overwrite the time pass.
    $key = $r['engine'];
    if ($key === 'native' && ($r['pass'] ?? 'heap') === 'heap') { $key = 'native_heap'; }
    $data[$r['workload']][(int)$r['n']][$key] = $r;
}

/** collects the set of sizes seen for a workload, sorted ascending. */
function sizes_of(array $byN): array {
    $s = array_keys($byN);
    sort($s, SORT_NUMERIC);
    return $s;
}
function fmt($v, int $dec = 2): string {
    return $v === null ? '—' : number_format((float)$v, $dec);
}
function speedup($zend, $ours): string {
    if ($zend === null || $ours === null || (float)$ours == 0.0) { return '—'; }
    return number_format((float)$zend / (float)$ours, 1) . '×';
}

$commit = trim(@shell_exec('git rev-parse --short HEAD 2>/dev/null') ?: '') ?: 'unknown';
$cpu = 'unknown';
if (is_readable('/proc/cpuinfo')) {
    foreach (file('/proc/cpuinfo') as $l) {
        if (str_starts_with($l, 'model name')) { $cpu = trim(explode(':', $l, 2)[1]); break; }
    }
}

echo "# sdsearch benchmarks\n\n";
echo "Generated by `benches/run.sh` → `tools/bench_report.php`. Reproducible: deterministic corpus, "
   . "fixed iterations, warm-up discarded. See [README.md](README.md) for the corpus and query definitions.\n\n";
echo "| | |\n|---|---|\n";
echo "| Date | " . date('Y-m-d H:i') . " |\n";
echo "| Commit | `$commit` |\n";
echo "| Host | " . php_uname('s') . ' ' . php_uname('r') . " |\n";
echo "| CPU | $cpu |\n";
echo "| PHP | " . PHP_VERSION . " |\n\n";

echo "**Engines.** `native` = the Rust core (examples/bench_engine) — reports the EXACT Rust heap. "
   . "`sdsearch` = our PHP extension. `zend` = Zend_Search_Lucene (pure PHP).\n\n";
echo "**Memory columns.** `heap` (native only) = peak Rust heap attributed to the op "
   . "(`memory_get_peak_usage()` cannot see this). `rss` = process peak RSS (VmHWM), the "
   . "cross-engine-comparable footprint. `php_peak` (PHP engines) omitted from tables because it "
   . "understates sdsearch (Rust heap is invisible to it); it is in results.jsonl for reference.\n\n";

// ---- rebuild / churn: time + memory, one row per size ----
foreach (['rebuild' => 'Rebuild (build the whole index from the KB base)',
          'churn'   => 'Churn (delete 1% of docs + add 1% + commit)'] as $wl => $title) {
    if (empty($data[$wl])) { continue; }
    echo "## $wl — $title\n\n";
    echo "| docs | native ms | native heap MB | native rss MB | sdsearch ms | sdsearch rss MB | zend ms | zend rss MB | speedup vs zend | doc_count |\n";
    echo "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n";
    foreach (sizes_of($data[$wl]) as $n) {
        $row = $data[$wl][$n];
        $na = $row['native'] ?? null;        // time pass: honest ms + rss
        $naH = $row['native_heap'] ?? null;  // heap pass: accurate heap
        $sd = $row['sdsearch'] ?? null; $ze = $row['zend'] ?? null;
        $dc = $na['doc_count'] ?? $naH['doc_count'] ?? $sd['doc_count'] ?? $ze['doc_count'] ?? null;
        printf("| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |\n",
            number_format($n),
            fmt($na['ms'] ?? null, 2),
            fmt(isset($naH['heap_peak_kb']) ? $naH['heap_peak_kb'] / 1024 : null, 1),
            fmt(isset($na['rss_peak_kb']) ? $na['rss_peak_kb'] / 1024 : null, 1),
            fmt($sd['ms'] ?? null, 2),
            fmt($sd['rss_peak_mb'] ?? null, 1),
            fmt($ze['ms'] ?? null, 2),
            fmt($ze['rss_peak_mb'] ?? null, 1),
            speedup($ze['ms'] ?? null, $sd['ms'] ?? null),
            $dc === null ? '—' : number_format((int)$dc));
    }
    echo "\n";
}

// ---- search: one table per paging depth (top-20, top-100); a row per (size, class) ----
if (!empty($data['search'])) {
    echo "## search — term latency by result class (many / few / none)\n\n";
    echo "p50 latency in ms, measured at two realistic paging depths. `hits` is the TRUE match "
       . "count for the class (must be identical across engines — correctness gate). Each query "
       . "reopens the index, as the engines do per request; at larger N the index-open cost "
       . "dominates low-hit queries. Zend's `find()` has no top-K limit, so its top-20 and "
       . "top-100 latencies coincide.\n\n";
    foreach (['top20' => 'top-20', 'top100' => 'top-100'] as $depth => $title) {
        echo "### $title\n\n";
        echo "| docs | class | native p50 | sdsearch p50 | zend p50 | speedup vs zend | hits |\n";
        echo "|---:|---|---:|---:|---:|---:|---:|\n";
        foreach (sizes_of($data['search']) as $n) {
            $row = $data['search'][$n];
            foreach (['many', 'few', 'none'] as $cls) {
                $na = $row['native'][$cls][$depth] ?? null; $sd = $row['sdsearch'][$cls][$depth] ?? null; $ze = $row['zend'][$cls][$depth] ?? null;
                $hits = $row['native'][$cls]['hits'] ?? $row['sdsearch'][$cls]['hits'] ?? $row['zend'][$cls]['hits'] ?? null;
                printf("| %s | %s | %s | %s | %s | %s | %s |\n",
                    number_format($n), $cls,
                    fmt($na['p50_ms'] ?? null, 4),
                    fmt($sd['p50_ms'] ?? null, 4),
                    fmt($ze['p50_ms'] ?? null, 4),
                    speedup($ze['p50_ms'] ?? null, $sd['p50_ms'] ?? null),
                    $hits === null ? '—' : number_format((int)$hits));
            }
        }
        echo "\n";
    }
}

// ---- skips ----
if ($skips) {
    echo "## Skipped runs\n\n";
    echo "| engine | workload | docs | reason |\n|---|---|---:|---|\n";
    foreach ($skips as $s) {
        printf("| %s | %s | %s | %s |\n", $s['engine'], $s['workload'], number_format((int)$s['n']), $s['reason'] ?? '');
    }
    echo "\n";
}
